### ISSUE TITLE
WebSphere: WebjarsResourceFinder - can't locate resource

### ISSUE THREAD

**Issue by a-brandt** [l0rdn1kk0n/wicket-webjars#10]
I tried to use wicket-bootstrap 0.9.1 on a WebSphere server but WebjarsResourceFinder could not locate the bootstrap.css or bootstrap.js file.

```
[2/5/14 17:51:18:946 CET] 0000005c SystemOut     O [WebContainer : 5] 05.02.14 17:51:18 7835  DEBUG WebjarsResourceFinder - can't locate resource for: de/agilecoders/wicket/webjars/request/resource/webjars/bootstrap/null/css/bootstrap.css; /webjars/bootstrap/null/css/bootstrap.css could not be found. Make sure you've added the corresponding WebJar and please check for typos. 
java.lang.IllegalArgumentException: /webjars/bootstrap/null/css/bootstrap.css could not be found. Make sure you've added the corresponding WebJar and please check for typos.
    at de.agilecoders.wicket.webjars.WebJarAssetLocator.throwNotFoundException(WebJarAssetLocator.java:145)
    at de.agilecoders.wicket.webjars.WebJarAssetLocator.getFullPath(WebJarAssetLocator.java:166)
```

Are there any known problems with WebSphere?

**Comment by heryqk** [comment]
Was this issues ever resolved on WebSphere or is this still an issue ? 

I'm currently having the issue on WebSphere 8.0.0.12, with Wicket-Bootstrap 0.9.16

**Comment by martin-g** [comment]
which version of wicket-webjars do you use ?

**Comment by heryqk** [comment]
wicket-webjars-0.4.8

Can't find references for bootstrap.css, bootstrap.js (which I could work around), but I am also getting the same for FontAwesome, which I can't work around.

If I run the same app in Jetty or Tomcat, it all works fine but I get the following on WebSphere:

GET http://win-jutvr554qmc:9080/OSCWebUISample/wicket/resource/de.agilecoders.w…WebjarsCssResourceReference/webjars/font-awesome/null/css/font-awesome.css 
win-jutvr554qmc/:6 GET http://win-jutvr554qmc:9080/OSCWebUISample/wicket/resource/de.agilecoders.w…ource.WebjarsCssResourceReference/webjars/bootstrap/null/css/bootstrap.css 
win-jutvr554qmc/:14 GET http://win-jutvr554qmc:9080/OSCWebUISample/wicket/resource/de.agilecoders.w….WebjarsJavaScriptResourceReference/webjars/bootstrap/null/js/bootstrap.js 404 (Not Found)
?1:47 Uncaught TypeError: $(...).dropdown is not a function(anonymous function) @ ?1:47fire @ jquery-1.12.0-ver-1465478824000.js:3232self.fireWith @ jquery-1.12.0-ver-1465478824000.js:3362jQuery.extend.ready @ jquery-1.12.0-ver-1465478824000.js:3582completed @ jquery-1.12.0-ver-1465478824000.js:3617

**Comment by martin-g** [comment]
Please try with 0.4.9.

**Comment by heryqk** [comment]
Same result.

**Comment by martin-g** [comment]
In that case it is not fixed for WebSphere :-/

**Comment by heryqk** [comment]
Should an issue be created ? If so where ?

**Comment by martin-g** [comment]
Here, in this project.
But none of us uses WebSphere, so we will need your help to debug and fix it.

**Comment by heryqk** [comment]
I'm happy to help. 
To be honest though, my understanding of webjars and loading of static jar resources is very limited. I will need some guidance to get through this.

**Comment by klopfdreh** [comment]
@heryqk - can you try to set the strict classloader flag as mentioned here:

http://www-01.ibm.com/support/docview.wss?uid=swg1PM03656

**Comment by heryqk** [comment]
I get the same result. See logs in [Issue 43](https://github.com/l0rdn1kk0n/wicket-webjars/issues/43).
