### ISSUE TITLE
OSGi classloader problems, possible workaround

### ISSUE THREAD

**Issue by ialexandrakis** [l0rdn1kk0n/wicket-webjars#15]
In the OSGi world, there should be a feature for accessing "bundle://" urls. There is also a pull request, but regarding only vfs storage, which is not the default handling in all containers.

Since wicket as a web application framework is NOT osgi friendly, (there are a lot of DynamicImport-Package: * in the jars, which creates a lot of problems with the loading of classes if there are two or more versions of the same class used by wicket), I decided to isolate wicket in a WAB and use it as such.

The only problem I found was that the *classLoaders()* in **WebjarsSettings** could not find the actual resources of the webjars (bootstrap.jar for example). This happened because all these jars (wicket-webjars-XXX jar which tries to find bootstrap.jar etc) were inside WEB-INF/lib and their resources were not accessible from the parent WAB, or from one another, since those jars are 'resources' to the wab and as such, we would have to drill down in the WEB-INF/lib and access those jars to get the actual resources.
Here comes another problem: if you have to find the 'physical' file inside the osgi container, the osgi specification is not strict. It states that the framework must cache bundles, however it does not specify how. So, every container could have its own implementation (perhaps even in memory, which would be even more difficult to handle, but let's not consider this case).

##### A not-so-elegant-but-quick-and-usable solution (more of a hack/workaround than a fix, since in osgi is a bad idea *to mess with classloaders*) is the following:
1. There is a property which defines the persistent storage used by the framework: http://www.osgi.org/javadoc/r4v43/core/org/osgi/framework/Constants.html#FRAMEWORK_STORAGE (org.osgi.framework.storage).
2. Use the above to iterate through the bundle's 'physical' directory and find all the jars which hold the webjars resources and add them to the array of "classLoaders()" in WebjarsSettings
3. This would probably need to import some dependencies to maven too.

dependencies:

```sh
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.core</artifactId>
      <version>4.3.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.4</version>
    </dependency>
```

de.agilecoders.wicket.webjars.settings.WebjarsSettings.java:
```sh
    public ClassLoader[] classLoaders() {
        ClassLoader[] array;
        List<ClassLoader> cls = new LinkedList<ClassLoader>();
        cls.add(Thread.currentThread().getContextClassLoader());
        cls.add(WebJarAssetLocator.class.getClassLoader());
        cls.add(getClass().getClassLoader());
        try {
            Bundle b = FrameworkUtil.getBundle(this.getClass());
            File cacheDir = new File(b.getBundleContext().getProperty("org.osgi.framework.storage"));
            Collection<File> cachedFiles = FileUtils.listFiles(cacheDir, new String[] { "jar" }, true);
            for (File file : cachedFiles) {
                URL[] urls = { file.toURI().toURL() };
                ClassLoader loader = new URLClassLoader(urls);
                cls.add(loader);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        array = cls.toArray(new ClassLoader[cls.size()]);
    }
```

This gets of course ALL the jars in the cache and not of the specific bundle's WEB-INF/lib (which is overkill), just pasted it here for reference. The container I work on is **Apache Karaf (felix)**

**Comment by martin-g** [comment]
Please send a Pull Request if something has to be improved for better OSGi support.
I don't use OSGi and I'm not in position to provide a good solution.
Thank you!
