### ISSUE TITLE
large dependency set added

### ISSUE THREAD

**Issue by tkruse** [l0rdn1kk0n/wicket-webjars#24]
Hi,

I like wicket-webjars. As a comment, I noticed today it pulls several library jars:
```
Size      Name
313898 dom4j-1.6.1.jar
644148 javassist-3.12.1.GA.jar
102696 reflections-0.9.8.jar
 48853  wicket-webjars-0.4.3.jar
```
Making this a 1MB dependency (not excessive, but still not nice).
I believe that seems excessive for the normal usage of wicket-webjars (unless I miss something), so it would be nice if there was a lightweight version.

You can close this issue when no time or not enough interest.

**Comment by martin-g** [comment]
The PR has been merged long time ago.
