### ISSUE TITLE
wicket-webjars 0.5.0 only for wicket7?

### ISSUE THREAD

**Issue by tkruse** [l0rdn1kk0n/wicket-webjars#30]
I noticed wicket-webjars 0.5.0 is out, but no commits on the master branch of this repo exist. Only the wicket7 branch has those. It would be nice if that could somehow be explained in the README file of the master branch, whether this is only compatible with wicket7.

Because as a developer I see there is a new version, so I try to go see the changelog, but find no information about 0.5.0 in this repo at a glance (neither readme, nor changelog, nor commit messages).

**Comment by martin-g** [comment]
Yes, 0.5.x is for Wicket 7.x. 
0.4.x will be for Wicket 6.x.
I have no much time to do everything properly.
Pull Requests are welcome!
