### ISSUE TITLE
Multiple JS

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-webjars#31]
How do I load multiple javascript in on WebjarsJavaScriptResourceReference?

**Comment by martin-g** [comment]
By overriding its dependencies (see `#getDependencies()`).

**Comment by Shengche** [comment]
Thanks Martin

On Sun, Apr 26, 2015 at 3:20 AM, Martin Grigorov <notifications@github.com>
wrote:

> By overriding its dependencies (see #getDependencies()).
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/l0rdn1kk0n/wicket-webjars/issues/31#issuecomment-96265654>
> .
>



-- 
--------------------------------------------------------------------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------------------------------->
We do this not because it is easy. We do this because it is hard.
--------------------------------------------------------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->
