### ISSUE TITLE
Unable to use webjars with deep hierarchy (more than 5 levels)

### ISSUE THREAD

**Issue by erikgb** [l0rdn1kk0n/wicket-webjars#32]
We have a webjar structure deeper than 5 (currently hard-coded value for FileAssetPathCollector#MAX_DIRECTORY_DEPTH), and our Wicket application is unable to start when loading webjar content from file system. Why is this max depth value set at all, and it should at least be configurable.

**Comment by martin-g** [comment]
I guess it was set to avoid wasting time in traversing deep file structures.

Pull request would be welcome!

**Comment by erikgb** [comment]
Thanks! I will be submitting a pull request soon. Suggested solution:
- No 'max directory depth' limit as default
- Adding a second constructor allowing for setting 'max directory depth'

As an alternative, the 'max directory depth' limit default can be set to 5 - which will make the fix 100% backwards compatible.

What do you think?

**Comment by martin-g** [comment]
I think it is safe to remove this restriction.
Most webjars use shallow hierarchy.

I have to re-read the related code before applying such change though!
