### ISSUE TITLE
PDF.JS

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-webjars#36]
Hello

I try to using PDF.JS in wicket project, but it seems cannot resolve the project name -- pdf-js
how can i do for it

**Comment by martin-g** [comment]
What did you try?

**Comment by Shengche** [comment]
Sorry I did the wrong way, after i changed the code to

super("pdf-js/current/build/pdf.js");

it works!

But, when i try to use it as javascript resorce there were error, showing
below

[2015-09-13T02:43:43.647+0800] [glassfish 4.1] [INFO] []
[com.google.javascript.jscomp.JsAst] [tid: _ThreadID=2177
_ThreadName=jscompiler] [timeMillis: 1442083423647] [levelValue: 800] [[
  Error parsing input.js: Compilation produced 10 syntax errors.
(input.js#1)]]

[2015-09-13T02:43:43.650+0800] [glassfish 4.1] [SEVERE] []
[com.google.javascript.jscomp] [tid: _ThreadID=26
_ThreadName=http-listener-1(1)] [timeMillis: 1442083423650] [levelValue:
1000] [[
  input.js:1116: ERROR - Parse error. missing name after . operator
    if (typeof globalScope.Promise.prototype.catch !== 'function') {
                                             ^
]]

[2015-09-13T02:43:43.651+0800] [glassfish 4.1] [SEVERE] []
[com.google.javascript.jscomp] [tid: _ThreadID=26
_ThreadName=http-listener-1(1)] [timeMillis: 1442083423651] [levelValue:
1000] [[
  input.js:1117: ERROR - Parse error. syntax error
      globalScope.Promise.prototype.catch = function (onReject) {
                 ^
]]

[2015-09-13T02:43:43.651+0800] [glassfish 4.1] [SEVERE] []
[com.google.javascript.jscomp] [tid: _ThreadID=26
_ThreadName=http-listener-1(1)] [timeMillis: 1442083423651] [levelValue:
1000] [[
  input.js:1121: ERROR - Parse error. missing ) in parenthetical
    return;
    ^
]]



On Sun, Sep 13, 2015 at 2:30 AM, Martin Grigorov <notifications@github.com>
wrote:

> What did you try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/l0rdn1kk0n/wicket-webjars/issues/36#issuecomment-139808482>
> .
>



-- 
--------------------------------------------------------------------------------------------->
To boldly go where no man has gone before.
--------------------------------------------------------------------------------------------->
We do this not because it is easy. We do this because it is hard.
--------------------------------------------------------------------------------------------->
front713@gmail.com
--------------------------------------------------------------------------------------------->

**Comment by martin-g** [comment]
Sorry, I have no experience with PDF.js...

**Comment by Shengche** [comment]
Okay,thanks.
