### ISSUE TITLE
Refreshing BootstrapSelect broken in 0.10.5/6

### ISSUE THREAD

**Issue by bkempe** [l0rdn1kk0n/wicket-webjars#38]
Steps to reproduce:
1. Go to https://wb-mgrigorov.rhcloud.com/select
2. click "Refresh first select"
3. console shows "Wicket.Ajax: Wicket.Ajax.Call.processComponent: Component with id [[default7e]] was not found while trying to perform markup update. Make sure you called component.setOutputMarkupId(true) on the component whose markup you are trying to update."

**Comment by martin-g** [comment]
BootstrapSelect is part of wicket-bootstrap project, not wicket-webjars.

**Comment by bkempe** [comment]
Oops, sorry.
