### ISSUE TITLE
Unblock .map files

### ISSUE THREAD

**Issue by ceefour** [l0rdn1kk0n/wicket-webjars#41]
```
org.apache.wicket.request.resource.PackageResource$PackageResourceBlockedException: Access denied to (static) package resource de/agilecoders/wicket/webjars/request/resource/webjars/backbone/1.2.3/backbone-min.map. See IPackageResourceGuard
```

I think `WicketWebjars.install()` should do this automatically ?

**Comment by ceefour** [comment]
I wonder if `+*.map` should be default in `SecurePackageResourceGuard` itself?

**Comment by l0rdn1kk0n** [comment]
i don't think that you want to allow sourcemaps on your production system? I could think about a dev/prod toggle for sourcemaps, what do you think?

**Comment by ceefour** [comment]
@l0rdn1kk0n I think if wicketConfiguration == `DEVELOPMENT`, the sourcemap should be unblocked

**Comment by martin-g** [comment]
It was added at point in Wicket and removed after that with the agreement that the application should enable it if it decides so.

The idea of the .map file is to be able to debug the generated code. In this case backbone.js is generated by CoffeeScript sources.
And the question in this example is: Why backbone.min.js needs a .map file? You cannot debug minified files.
Usually the the non-minified file refers to its .map file and the minified doesn't.

**Comment by ceefour** [comment]
regarding min & map : `backbone-min.map` does exist.. It seems to map minified names back to original names.

**Comment by ceefour** [comment]
I agree that `DEPLOYMENT` should block .map by default.
But ExceptionSettings is enabled by default, and I'd argue that security-wise, leaving ExceptionSettings enabled is more "insecure" than a JS map file. I mean, many people is using non-minified JS in production, and that's not a problem.

So if ExceptionSettings is enabled in dev and disabled in prod (by Wicket's defaults), I'd argue that .map files should be treated similar. I don't see any harm in allowing .map for `DEVELOPMENT` (only) by default.

**Comment by l0rdn1kk0n** [comment]
I think it's a valid point to use sourcemaps in development mode, the users don't have to use the minified versions in development mode, so it should be possible to load them.

@martin-g please review the proposed solution.

**Comment by martin-g** [comment]
I'll keep this issue opened for some more. 
I want to dig what was the reason to revert the allowance of `.map` in the past.

**Comment by martin-g** [comment]
It seems we will allow `.map` files by default in Wicket 6.23/7.3.
I'll revert the improvement here once I add it to Wicket.

**Comment by ceefour** [comment]
Awesome! :)

**Comment by martin-g** [comment]
https://issues.apache.org/jira/browse/WICKET-6122

**Comment by martin-g** [comment]
Reverted!
