### ISSUE TITLE
Wicket-webjars has issues with Wildfly 10

### ISSUE THREAD

**Issue by PolyPik** [l0rdn1kk0n/wicket-webjars#44]
I followed the instructions to a t, but still getting this message on the console.
`
20:55:01,635 WARN  [org.apache.wicket.request.resource.ResourceReferenceRegistry] (default task-2) A ResourceReference wont be created for a resource with key [scope: de.agilecoders.wicket.webjars.request.resource.WebjarsCssResourceReference; name: webjars/bootstrap/3.3.6/css/bootstrap.css; locale: null; style: null; variation: null] because it cannot be located.`

So I decided to do a bit of research on my issue.

It appears that wicket-webjars had issues with Wildfly in the past. Apparently you managed to implement a fix of some sort in #27  back in October 2014. Although, I'm not sure if the issue relating to that fix is of any relevance to my problems.

Anyways, my project is a Wicket 7.3.0 project and the application server is Wildfly 10.0.0.Final. I tried out your sample project on the Wildfly server and it failed to work (i.e. the jQuery didn't load and neither did the bootstrap CSS). But when I deployed the same war file to a Tomcat server, lo and behold, the countdown actually works and I can see the glyphicons symbols.

EDIT: Yes, I do use Maven.
EDIT2: I came across [this conversation](https://github.com/webjars/webjars-locator/issues/18) in the webjars group.

**Comment by martin-g** [comment]
Hi @PolyPik,

I've just fixed the issue in `wicket-7.x` branch.
Could you please build it locally and verify that it works for you too ?
Thank you and sorry for the delay!

**Comment by martin-g** [comment]
Just tested the fix with Wildfly 8.1 and 9.0.2 as well. 
Seems to work good!

**Comment by PolyPik** [comment]
Issue is fixed for Wildfly 10.

**Comment by martin-g** [comment]
Thanks for confirming!
