### ISSUE TITLE
Make 'wicket-7.x' the default branch

### ISSUE THREAD

**Issue by martin-g** [l0rdn1kk0n/wicket-webjars#46]
Hi @l0rdn1kk0n !

How is it going?

Could you please make `wicket-7.x` branch the default one in GitHub ?
Then I will delete `master`.

I'll need the same for wicket-jquery-selectors and wicket-bootstrap too. Maybe you could just make me co-admin of all your Wicket related projects :-)

**Comment by martin-g** [comment]
@l0rdn1kk0n Ping!

**Comment by l0rdn1kk0n** [comment]
done.

**Comment by martin-g** [comment]
Thanks!
I've created separate issues for Wicket Bootstrap and JQuery Selectors.

**Comment by l0rdn1kk0n** [comment]
i've changed all default branches to wicket-7

**Comment by martin-g** [comment]
Thank you!
