### ISSUE TITLE
Not serving resources when running under embedded jetty

### ISSUE THREAD

**Issue by jn73** [l0rdn1kk0n/wicket-webjars#49]
I have a legacy wicket 6 application that is running fine under jboss-7 (also tried tomcat). Now I would like to run it through an embedded jetty-server but then wicket keeps ignoring any requests to /webjars:

DEBUG - RequestCycle               - No suitable handler found for URL webjars/bootstrap/3.2.0/js/bootstrap.min.js, falling back to container to process this request

I have this in my application init:

		WebjarsSettings settings = new WebjarsSettings();
		WicketWebjars.install(this, settings);

..And the webjars as maven deps. Works just fine wen i deploy the war.

Any ideas?

**Comment by martin-g** [comment]
You don't mention which versions you use but I have the feeling that
wicket-webjars is not latest. Please update it and try again.
If this doesn't help then please create a quickstart app and attach it here.

**Comment by jn73** [comment]
Wicket 6.25.0 and wicket-webjars 0.4.10.

I'll attach  quickstart project which is not serving http://localhost:8080/webjars/bootstrap/3.2.0/css/bootstrap.css

Running with: mvn package exec:java -Dexec.mainClass="se.metria.fpris.admin.Start" -Dexec.classpathScope="test"

[quickstart.zip](https://github.com/l0rdn1kk0n/wicket-webjars/files/638733/quickstart.zip)

**Comment by martin-g** [comment]
This is not a bug in Wicket Webjars.
The support for usages like `<link href="webjars/bootstrap/3.2.0/css/bootstrap.css" rel="stylesheet">` comes from Servlet 3. Containers implementing v.3 should provide all resources inside `/META-INF/resources/` as static resources.
In your demo app you use `<jetty.version>7.6.16.v20140903</jetty.version>` which is implementing Servlet 2.x. 
Unfortunately just upgrading Jetty to a newer version is not enough. Embedded Jetty doesn't act as a "normal web container" out of the box. Sometimes you need to add explicit configuration (in Start.java) to enable some features, like this one. 
Quick googling led me to: https://dev.eclipse.org/mhonarc/lists/jetty-dev/msg00902.html but it doesn't tell what to do to make it work.

**Comment by jn73** [comment]
Thanks for your answer - I'll look for a solution in jetty.

**Comment by martin-g** [comment]
If you use Webjars(Css|JavaScript)ResourceReference instead of `<link .../>` then it works fine too.
