### ISSUE TITLE
Wicket 6.24.0 with wicket-webjars 0.4.10 "current" not detected

### ISSUE THREAD

**Issue by Shengche** [l0rdn1kk0n/wicket-webjars#50]
Hello
I used Wicket 6.24.0 and wicket-webjars 0.4.8 works well with below debug message:

> 23:22:41,656  INFO wicket-webjars:81 - initialize wicket webjars with given settings: WebjarsSettings{readFromCacheTimeout=3 seconds, resourceStreamProvider=ClassLoader, recentVersionPlaceHolder='current', assetPathCollectors=[de.agilecoders.wicket.webjars.collectors.FileAssetPathCollector@2d25497c, de.agilecoders.wicket.webjars.collectors.JarAssetPathCollector@355094dc, de.agilecoders.wicket.webjars.collectors.VfsAssetPathCollector@1125f1d8], webjarsPackage='META-INF.resources.webjars', webjarsPath='META-INF/resources/webjars', resourcePattern=.*, webjarsPathPattern=/webjars/([^/]*)/([^/]*)/(.*), useCdnResources=false, cdnUrl='//cdn.jsdelivr.net:80'}
23:22:41,672  INFO wicket-jquery-selectors:59 - initialize wicket jquery selectors with given settings: de.agilecoders.wicket.jquery.settings.WicketJquerySelectorsSettings@253eb419

But, when I changed wicket-webjars version to 0.4.10 something happened:

> 23:16:12,144  INFO wicket-webjars:81 - initialize wicket webjars with given settings: WebjarsSettings{readFromCacheTimeout=3 seconds, resourceStreamProvider=ClassLoader, recentVersionPlaceHolder='current', assetPathCollectors=[de.agilecoders.wicket.webjars.collectors.ClasspathAssetPathCollector@3a649ceb, de.agilecoders.wicket.webjars.collectors.VfsAssetPathCollector@4c926712, de.agilecoders.wicket.webjars.collectors.FileAssetPathCollector@6aec6bac], webjarsPackage='META-INF.resources.webjars', webjarsPath='META-INF/resources/webjars', resourcePattern=META-INF/resources/webjars/.*, webjarsPathPattern=/webjars/([^\/]*)\/([^\/]*)\/(.*), useCdnResources=false, cdnUrl='//cdn.jsdelivr.net:80'}
23:16:12,167  INFO wicket-jquery-selectors:59 - initialize wicket jquery selectors with given settings: de.agilecoders.wicket.jquery.settings.WicketJquerySelectorsSettings@6b0029d9
23:16:12,198 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/modernizr/current/modernizr.js
23:16:12,201 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/bootstrap/current/js/bootstrap.js
23:16:12,201 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/bootstrap/current/css/bootstrap.css
23:16:12,203 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/jquery-ui/current/jquery-ui.js
23:16:12,204 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/ace/current/src-min-noconflict/ace.js
23:16:12,205 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/ace/current/src-min-noconflict/ext-static_highlight.js
23:16:12,205 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/ace/current/src-min-noconflict/ext-statusbar.js
23:16:12,206 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/ace/current/src-min-noconflict/mode-java.js
23:16:12,206 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/ace/current/src-min-noconflict/theme-github.js
23:16:12,207 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/ace/current/src-min-noconflict/ext-error_marker.js
23:16:12,207 DEBUG WicketWebjars:77 - no version found for webjars resource: /webjars/jquery-blockui/current/jquery.blockUI.js

After I reviewed the previous issues, I changed my code in Application#init(), and it works again

> WebjarsSettings settings = new WebjarsSettings();
//fix for wicket-webjar 0.4.10 settings
settings.resourcePattern(Pattern.compile(".*"));
WicketWebjars.install(this, settings);

The debug message as following

> 00:10:39,936  INFO WicketApplication:158 - Resource Pattern : META-INF/resources/webjars/.*
00:10:39,936  INFO WicketApplication:161 - Resource Pattern : .*
00:10:39,966  INFO wicket-webjars:81 - initialize wicket webjars with given settings: WebjarsSettings{readFromCacheTimeout=3 seconds, resourceStreamProvider=ClassLoader, recentVersionPlaceHolder='current', assetPathCollectors=[de.agilecoders.wicket.webjars.collectors.ClasspathAssetPathCollector@210ddc57, de.agilecoders.wicket.webjars.collectors.VfsAssetPathCollector@2fa66efd, de.agilecoders.wicket.webjars.collectors.FileAssetPathCollector@41fb8c81], webjarsPackage='META-INF.resources.webjars', webjarsPath='META-INF/resources/webjars', resourcePattern=.*, webjarsPathPattern=/webjars/([^\/]*)\/([^\/]*)\/(.*), useCdnResources=false, cdnUrl='//cdn.jsdelivr.net:80'}

**Comment by martin-g** [comment]
Please provide a quickstart application!
Thank you!

**Comment by pqian** [comment]
@martin-g: You have applied FIX #44 in branch 2.x, 0.5.x, und 0.4.x. Could you make a new release for 0.4.x? The 0.4.10 was released in Aug 2016, 1 year ago. The fix is important for loading webjars in JBoss.

**Comment by martin-g** [comment]
0.4.11 is on its way to Maven Central!
Enjoy!

**Comment by pqian** [comment]
@martin-g 
...but the fix is not in the release 0.4.11. see [VfsAssetPathCollector](https://github.com/l0rdn1kk0n/wicket-webjars/blob/wicket-webjars-parent-0.4.11/library/src/main/java/de/agilecoders/wicket/webjars/collectors/VfsAssetPathCollector.java)
in branch wicket-6.x the [VfsAssetPathCollector](https://github.com/l0rdn1kk0n/wicket-webjars/blob/wicket-6.x/library/src/main/java/de/agilecoders/wicket/webjars/collectors/VfsAssetPathCollector.java) was fixed.

**Comment by martin-g** [comment]
Duh!
No idea how this happened!

I've released latest `wicket-6.x` branch.
`git pull --rebase` returned that everything is up-to-date. I even was able to push dependencies updates in the pom.xml.

I'll try to find what went wrong later.
If you find it before me please let me know and I will cut 0.4.12.

**Comment by martin-g** [comment]
OK. 0.4.12 is released!
